require 'simplecov'
SimpleCov.root(File.join(File.dirname(__FILE__),"..","lib"))
SimpleCov.command_name "Utilrb"
SimpleCov.start

require './test_array'
require './test_config'
require './test_dir'
require './test_enumerable'
require './test_exception'
require './test_gc'
require './test_hash'
require './test_kernel'
require './test_logger'
require './test_misc'
require './test_module'
require './test_object'
require './test_objectstats'
require './test_pkgconfig'
require './test_proc'
require './test_set'
require './test_time'
require './test_unbound_method'
require './test_weakref'
require './test_thread_pool'
require './test_event_loop'
